### ISSUE TITLE
SSR2OSR

### ISSUE THREAD

**Issue by molstmare** [GeoppGmbH/RTCM-SSR-Python-Demonstrator#1]
When I try to convert a binary file containing RTCM messagens I can decode, however when trying to convert to OSR a message appears saying, "No available ephemeris --> no influence of SSR parameters is computed, return decoded RTCM-SSR messages."

I checked the decoded message and has ephemeris messages.
What am I doing wrong?

**Comment by fenggolang** [comment]
hello，When I try to convert a binary file containing RTCM messagens I can not decode，Can you share your decoding steps thanks

RINEX 3.04

![image](https://user-images.githubusercontent.com/16982786/139208840-910a8cba-5222-4aaa-8c21-2d6a40183844.png)

**Comment by fenggolang** [comment]
@molstmare Have you solved it？

**Comment by molstmare** [comment]
Yes, I was able to run the software correctly, I didn't have the problem that you showed in the image @fenggolang
